name: CI (alarm-triage)

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt
      - name: Run unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q
      - name: Run offline batch demo
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m scripts.alarm_triage.triage \
            --alarms "demo/alarms/*.json" \
            --out outputs/batch \
            --offline --emit-draft
      - name: Upload artifacts (outputs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/**
