name: CI (alarm-triage)

on:
  push:
  pull_request:

concurrency:
  group: ci-alarm-triage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create venv & install deps
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip wheel
          pip install -r requirements.txt

      - name: Run tests
        shell: bash
        run: |
          source .venv/bin/activate
          pytest -q

      - name: Offline batch triage (produce outputs)
        shell: bash
        run: |
          source .venv/bin/activate
          python -m scripts.alarm_triage.triage \
            --alarms "demo/alarms/*.json" \
            --out outputs/batch \
            --offline --emit-draft

      - name: Upload outputs artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/**
          if-no-files-found: warn
