name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-offline-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create venv & install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -q

      - name: Offline triage demo
        run: |
          source .venv/bin/activate
          python -m scripts.backup_configs --offline-from demo/configs --out configs
          python -m scripts.audit_baseline --configs configs/latest --report reports/baseline_report.csv
          python -m scripts.push_change --offline --before demo/configs/edge-rtr01.cfg --name edge-rtr01 \
            --ntp "1.1.1.1,1.0.0.1" --banner "Authorized access only" \
            --disable-http --fix-ssh --timestamps \
            --diffs diffs --write-after --after-out configs/after_demo \
            --plan-out reports/change_plan.md --plan-json reports/change_plan.json
          python -m scripts.audit_baseline --configs configs/after_demo --report reports/after_baseline_report.csv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            reports/*.csv
            reports/change_plan.*
            diffs/**
            configs/after_demo/**
          if-no-files-found: warn
