<<<<<<< HEAD
name: demo
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run offline demo
        run: |
          source .venv/bin/activate
          python -m scripts.backup_configs --offline-from demo/configs --out configs
          python -m scripts.audit_baseline --configs configs/latest --report reports/baseline_report.csv
          python -m scripts.push_change --offline --before demo/configs/edge-rtr01.cfg --name edge-rtr01 \
            --ntp "1.1.1.1,1.0.0.1" --banner "Authorized access only" \
            --disable-http --fix-ssh --timestamps \
            --diffs diffs --write-after --after-out configs/after_demo
          python -m scripts.audit_baseline --configs configs/after_demo --report reports/after_baseline_report.csv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: demo-artifacts
          path: |
            reports/*.csv
            diffs/**
            configs/after_demo/**
=======
name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy pytest-cov
      - name: Ruff
        run: ruff check .
      - name: Type check (non-blocking)
        run: mypy scripts ui || true
      - name: Pytest w/ coverage
        run: pytest --cov=scripts --cov=ui --cov-report=xml --cov-report=term-missing
      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: error
>>>>>>> 8cc0126 (UI overhaul)
